[package]
name = "abdulbasit_crate_2"
version = "0.1.0"
authors = ["abdulbasit01 <abdulbasit14827@gmail.com>"]
edition = "2018"
description="console message"
license="MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
